# Generated by Django 5.0.11 on 2025-01-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedgoods',
            name='unit_price',
            field=models.DecimalField(db_column='UnitPrice', decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawmaterials',
            name='unit_price',
            field=models.DecimalField(db_column='UnitPrice', decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
