# Generated by Django 5.0.11 on 2025-02-06 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_finishedgoods_unit_price_rawmaterials_unit_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredients',
            unique_together={('productid', 'rawmaterialid')},
        ),
    ]
