# Generated by Django 5.0.11 on 2025-02-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_ingredients_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedgoods',
            name='unit_price',
            field=models.FloatField(db_column='UnitPrice'),
        ),
    ]
