# Generated by Django 5.0.11 on 2025-02-06 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_finishedgoods_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='positionid',
            field=models.ForeignKey(db_column='PositionID', on_delete=django.db.models.deletion.CASCADE, to='content.positions'),
        ),
        migrations.AlterField(
            model_name='finishedgoods',
            name='unitid',
            field=models.ForeignKey(db_column='UnitID', on_delete=django.db.models.deletion.CASCADE, to='content.units'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='productid',
            field=models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, to='content.finishedgoods'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='rawmaterialid',
            field=models.ForeignKey(db_column='RawMaterialID', on_delete=django.db.models.deletion.CASCADE, to='content.rawmaterials'),
        ),
        migrations.AlterField(
            model_name='productproduction',
            name='employeeid',
            field=models.ForeignKey(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, to='content.employees'),
        ),
        migrations.AlterField(
            model_name='productproduction',
            name='productid',
            field=models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, to='content.finishedgoods'),
        ),
        migrations.AlterField(
            model_name='productsales',
            name='employeeid',
            field=models.ForeignKey(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, to='content.employees'),
        ),
        migrations.AlterField(
            model_name='productsales',
            name='productid',
            field=models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, to='content.finishedgoods'),
        ),
        migrations.AlterField(
            model_name='rawmaterialpurchases',
            name='employeeid',
            field=models.ForeignKey(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, to='content.employees'),
        ),
        migrations.AlterField(
            model_name='rawmaterialpurchases',
            name='rawmaterialid',
            field=models.ForeignKey(db_column='RawMaterialID', on_delete=django.db.models.deletion.CASCADE, to='content.rawmaterials'),
        ),
        migrations.AlterField(
            model_name='rawmaterials',
            name='unitid',
            field=models.ForeignKey(db_column='UnitID', on_delete=django.db.models.deletion.CASCADE, to='content.units'),
        ),
    ]
