# Generated by Django 5.0.11 on 2025-02-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_employees_positionid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterials',
            name='unit_price',
            field=models.FloatField(db_column='UnitPrice'),
        ),
    ]
