# Generated by Django 5.0.11 on 2025-03-05 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_rawmaterials_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterials',
            name='unit_price',
        ),
    ]
