# Generated by Django 5.0.11 on 2025-03-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_rawmaterials_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='sales_percentage',
            field=models.FloatField(db_column='SalesPercentage', default=0),
        ),
    ]
