# Generated by Django 5.0.11 on 2025-03-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_budget_sales_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsales',
            name='quantity',
            field=models.IntegerField(db_column='Quantity'),
        ),
    ]
