# Generated by Django 5.0.11 on 2025-04-05 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_productsales_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salaries',
            fields=[
                ('salaryid', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('purchase_count', models.IntegerField(default=0)),
                ('production_count', models.IntegerField(default=0)),
                ('sale_count', models.IntegerField(default=0)),
                ('total_activities', models.IntegerField(default=0)),
                ('bonus_percent', models.FloatField(default=0.0)),
                ('total_salary', models.FloatField(default=0.0)),
                ('is_paid', models.BooleanField(default=False)),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.employees')),
            ],
            options={
                'unique_together': {('employeeid', 'year', 'month')},
            },
        ),
    ]
