# Generated by Django 5.0.11 on 2025-04-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_salaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='bonus_per_activity',
            field=models.FloatField(db_column='BonusPerActivity', default=0),
        ),
    ]
