# Generated by Django 5.0.11 on 2025-04-05 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_budget_bonus_per_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='employeeid',
            field=models.ForeignKey(db_column='employeeid', on_delete=django.db.models.deletion.CASCADE, to='content.employees'),
        ),
    ]
