# Generated by Django 5.0.11 on 2025-04-24 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_alter_salaries_employeeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('creditid', models.AutoField(db_column='CreditID', primary_key=True, serialize=False)),
                ('amount', models.FloatField(db_column='Amount')),
                ('interest', models.FloatField(db_column='Interest')),
                ('credit_date', models.DateField(db_column='CreditDate')),
                ('months', models.IntegerField(db_column='Months')),
            ],
            options={
                'verbose_name': 'Кредит',
                'verbose_name_plural': 'Кредиты',
                'db_table': 'Credits',
            },
        ),
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('paymentid', models.AutoField(db_column='PaymentID', primary_key=True, serialize=False)),
                ('payment_date', models.DateField(db_column='PaymentDate')),
                ('credit_part', models.FloatField(db_column='CreditPart')),
                ('interest', models.FloatField(db_column='Interest')),
                ('total_amount', models.FloatField(db_column='TotalAmount')),
                ('remaining_credit', models.FloatField(db_column='RemainingCredit')),
                ('overdue_days', models.IntegerField(db_column='OverdueDays', default=0)),
                ('late_fee', models.FloatField(db_column='LateFee', default=0.0)),
                ('total_payment', models.FloatField(db_column='TotalPayment')),
                ('creditid', models.ForeignKey(db_column='CreditID', on_delete=django.db.models.deletion.CASCADE, to='content.credit')),
            ],
            options={
                'verbose_name': 'Платеж по кредиту',
                'verbose_name_plural': 'Платежи по кредитам',
                'db_table': 'CreditPayments',
            },
        ),
    ]
