# Generated by Django 5.0.11 on 2025-04-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_credit_creditpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditpayment',
            name='late_fee',
        ),
        migrations.AddField(
            model_name='credit',
            name='late_fee',
            field=models.FloatField(db_column='LateFee', default=0.0),
        ),
    ]
