# Generated by Django 5.0.11 on 2025-04-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_remove_creditpayment_late_fee_credit_late_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='is_paid_off',
            field=models.BooleanField(db_column='IsPaidOff', default=False),
        ),
        migrations.AddField(
            model_name='credit',
            name='next_due',
            field=models.DateField(blank=True, db_column='NextDue', null=True),
        ),
    ]
