# Generated by Django 5.0.11 on 2025-04-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_credit_is_paid_off_credit_next_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='initial_amount',
            field=models.FloatField(db_column='InitialAmount', default=0),
            preserve_default=False,
        ),
    ]
