# Generated by Django 5.0.11 on 2025-04-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_credit_initial_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpayment',
            name='penalty',
            field=models.FloatField(db_column='Penalty', default=0),
        ),
    ]
